# Site Settings
name: Kinflix
title: Kinflix | Kingsae's Tech blog
description: Kingsae's Tech blog
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: kingsae1004@gmail.com
# See: https://disqus.com/
disqus_username: Kingsae
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: xknkzqpw

# Social Media Settings
# Remove the item if you don't need it
github_username: kingsae1
linkedin_username: kingsae1
medium_username: kingsae

# Posts Settings
show_time_bar: true
show_modal_on_exit: false
show_modal_on_finish_post: true
two_columns_layout: true

# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kingsae1.github.io" # the base hostname & protocol for your site
google_analytics: "G-BN80Y1XNK3"
language: "kr"
categories_folder: category
sent_message_url: "/contact/message-sent/"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
collections:
  authors:
    output: true
paginate_path: "/page/:num/"
show_get_theme_btn: false
use_logo: false

# Content paginator
paginate_content:
  enabled: true
  debug: false
  collections:
    - posts
  auto: false
  separator: "--page-break--"
  permalink: "/:num/"
  seo_canonical: true
  properties:
    part:
      is_generated: true
    last:
      is_generated: true
    single:
      is_generated: true

# SASS
sass:
  style: compressed

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-paginate-content

# Exclude my node related stuff
exclude:
  [
    "package.json",
    "package-lock.json",
    "src",
    "node_modules",
    "initpost.sh",
    "Gemfile",
    "Gemfile.lock",
    "gulpfile.js",
    "README.md",
  ]

# Theme
version: v3.1.1
